name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operation_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operation_system: macos-latest
    runs-on: ${{ matrix.operation_system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result-${{ matrix.operation_system }}-Node-${{ matrix.nodejs_version }}
          path: test-results-${{ matrix.operation_system }}-node-${{ matrix.nodejs_version }}.xml